# Numpy

**Numpy stands for numerical python . It is a powerful python library used for mathematical computing . It supports multidimensional arrays and mathematical functions (mean , standard deviation)**



**Applications of python**

**1 Mathematics**

**2 Plotting(Matplotlib)**

**3 Backend(Connect 4 , Pandas , Digital Photography)**

**4 Machine Learning**

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
b=np.array([[5,6,7,8],[1,2,3,4]])
b

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

# To check array properties

In [4]:
a.shape

(4,)

**to get the shape of an array**

In [5]:
a.dtype

dtype('int32')

**Datatype of array**

In [6]:
a.ndim

1

**no of dimensions**

In [7]:
a.size

4

**size of the array**

In [8]:
a.itemsize


4

In [9]:
b.itemsize

4

In [10]:
# total size
a.nbytes

16

In [11]:
# datatype
a.dtype

dtype('int32')

# Array initialization shortcuts

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**array of zeroes 2*2 matrix**

In [13]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

**array of ones 3*2 matrix**

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**3*3 Identity matrix**

In [16]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

**any number matrix**

In [17]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.07058897, 0.90089929],
       [0.48703392, 0.33542102],
       [0.5769954 , 0.97434939],
       [0.94748268, 0.40135188]])

In [18]:
np.random.random_sample(a.shape)

array([0.37551771, 0.25482253, 0.66974908, 0.87546854])

In [19]:
# random integer values
np.random.randint(-4,8,size=(3,3))

array([[ 7, -2,  7],
       [ 0, -3,  5],
       [ 0, -4,  1]])

In [20]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [71]:
# evenly spaced numbers over a specified interval
np.linspace(0,5,10)


array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
#repeat an array in an matrix
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [22]:
matrix = np.ones([5,5])
matrix[1:4,1:4]=0
matrix[2,2]=9
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Copying of an array

In [23]:
a = np.array([1,2,3,4,5])
b = a 
b[0]=100
print (b)
print(a)

# Assigning a to b and then changes made to b aslo makes changes to a . Hence copy function to be used in numpy

[100   2   3   4   5]
[100   2   3   4   5]


In [24]:
a = np.array([1,2,3,4,5])
b = a.copy()
b[0]=100
print (b)
print(a)


[100   2   3   4   5]
[1 2 3 4 5]


# Acessing/Changing specific elements rows,columns etc

In [25]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [26]:
a.shape

(2, 7)

In [27]:
# getting a specific element
a[1,5]

13

In [28]:
a[1,-4]

11

In [29]:
# Getting a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
# Getting a specific column
a[ :,2]

array([ 3, 10])

In [31]:
# [startindex, endindex: step]
a[0,1:6:2]

array([2, 4, 6])

In [32]:
# change elemnts at a specific position
a[0,5]=20
a

array([[ 1,  2,  3,  4,  5, 20,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [33]:
#change elements in a column 
a[ :,2]=5
a

a[ :,2]=[1,3]
a



array([[ 1,  2,  1,  4,  5, 20,  7],
       [ 8,  9,  3, 11, 12, 13, 14]])

**3D Example**

In [34]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [35]:
# Get  a specific element 
b[:,0,:]


array([[1, 2],
       [5, 6]])

In [36]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [37]:
b[0,1,1]

4

In [38]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
b[:,1,:]

array([[9, 9],
       [8, 8]])

# Basic oprations on Array

In [39]:
c = np.array([4,5,6,7])
d = np.array([9,2,3,4])

In [40]:
c+d

array([13,  7,  9, 11])

In [41]:
c+=2
c

array([6, 7, 8, 9])

In [42]:
c-d

array([-3,  5,  5,  5])

In [43]:
c*d

array([54, 14, 24, 36])

In [44]:
c/d

array([0.66666667, 3.5       , 2.66666667, 2.25      ])

In [45]:
np.cos(c)

array([ 0.96017029,  0.75390225, -0.14550003, -0.91113026])

**Scalar Operations**

In [46]:
c+2

array([ 8,  9, 10, 11])

In [47]:
c*2

array([12, 14, 16, 18])

# Array Functions

**Aggregate functions / Statistics**

In [48]:
e = np.array([[4,5,6,7],[1,2,3,4]])

In [49]:
e.sum()

32

In [50]:
e.mean()

4.0

In [51]:
e.min()

1

In [52]:
e.max()

7

In [53]:
e.std()

1.8708286933869707

**Matrix operations**

In [54]:
A= np.array([[1,2],[3,4]])
B= np.array([[5,6],[7,8]])

In [55]:
A.dot(B)

array([[19, 22],
       [43, 50]])

**Linear Algebra**

In [56]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),3)
print(b)

# they both are not gonna get multiplied since they are not of the same size so use matmul
#(matrix multiply)
c=np.matmul(a,b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]
[[9. 9.]
 [9. 9.]]


In [57]:
#Find the determinant 
c = np.identity(3)
np.dot(c,c)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Reshaping array

In [58]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


**Vertically stacking vectors**

In [59]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

**Horizontal stacking of vectors**

In [60]:
h1 = np.zeros((2,4))
h2 = np.ones((2,2)  )

np.hstack([h1,h2])

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

# Miscallenous

**Load the File**

In [61]:
filedata= np.genfromtxt("text.txt",delimiter=",")
filedata= filedata.astype("int32")
print(filedata)

[[          1           2           3           4           5           6
            7           8           8          86           4           3
            4          53           3         423           4          23
  -2147483648]
 [         23           2          31           3           1           3
            5           1           3           1          13           1
           31          31          31          13           1           1
            2]
 [         32           2           3           2           2         323
           56           4          55           4          55          55
           63           4          54           5           5          12
           12]]


C:\Users\Gayatri\AppData\Local\Temp\ipykernel_18288\1160988044.py:2: RuntimeWarning: invalid value encountered in cast
  filedata= filedata.astype("int32")


**Boolean masking and indexing**

In [62]:
filedata >= 30

array([[False, False, False, False, False, False, False, False, False,
         True, False, False, False,  True, False,  True, False, False,
        False],
       [False, False,  True, False, False, False, False, False, False,
        False, False, False,  True,  True,  True, False, False, False,
        False],
       [ True, False, False, False, False,  True,  True, False,  True,
        False,  True,  True,  True, False,  True, False, False, False,
        False]])

In [63]:
filedata[filedata > 50]

array([ 86,  53, 423, 323,  56,  55,  55,  55,  63,  54])

In [64]:
# you can index with a list in numpy 
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [65]:
np.any(filedata > 50, axis=0)

array([False, False, False, False, False,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False])

In [66]:
np.all(filedata > 50 ,axis=0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [67]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False, False, False, False, False,
         True, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True, False,  True,
        False,  True,  True,  True, False,  True, False, False, False,
        False]])